name: weekly-cron-job
on:
    schedule:
        - cron: '* * * * *'
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: weekly-cron-job
              run: |
                  curl --request POST \
                  --url 'https://next-ecommerce-black.vercel.app/api/v1/cron'
